module.exports = {
/*  mySidebar: {
    themeConfig: [
      hideableSidebar: true,
    ],
    {
      type: 'autogenerated',
      dirName: './docs/', // génère une barre latérale à partir du dossier docs (ou versioned_docs/<version>)
    },
  },*/
/*  someSidebar: {
    "About datacraft": [
      'pagetemplate0',
      'pagetemplate1',
    ],
  },*/
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // génère une barre latérale à partir du dossier docs (ou versioned_docs/<version>)
    },
  ],

};
